---
- name: Create mongodb database and user
  community.mongodb.mongodb_user:
    database: "{{ mongodb_gravitee_database }}"
    name: "{{ mongodb_gravitee_user }}"
    password: "{{ mongodb_gravitee_password }}"
    roles: "{{ mongodb_gravitee_user_role }}"
    state: present
- name: "Configure Gravitee config files"
  template:
    src: templates/gravitee_{{ item }}.yml.j2
    dest: "{{ gravitee_install_dir }}/{{ item }}/config/gravitee.yml"
  loop:
    - gateway
    - rest-api

- name: "Configure Gravitee service files"
  template: 
    src: templates/gravitee_service.j2   
    dest: /etc/systemd/system/graviteeio-apim-{{ item }}.service
  loop:
    - gateway
    - rest-api
- name: "Configure Gravitee console UI constants file"
  template: 
    src: gravitee_console_ui_constants.json.j2   
    dest: "{{ gravitee_install_dir }}/console-ui/constants.json"

- name: "Start Gravitee services"
  systemd: 
    name: graviteeio-apim-{{ item }}.service
    state: restarted
  loop:
    - gateway
    - rest-api
