---
- name: Create mongodb database and user
  community.mongodb.mongodb_user:
    database: "{{ mongodb_gravitee_database }}"
    name: "{{ mongodb_gravitee_user }}"
    password: "{{ mongodb_gravitee_password }}"
    roles: "{{ mongodb_gravitee_user_role }}"
    state: present
- name: "Configure Gravitee config files"
  template:
    src: templates/gravitee_{{ item }}.yml.j2
    dest: "{{ gravitee_install_dir }}/{{ item }}/config/gravitee.yml"
  loop:
    - gateway
    - rest-api

- name: "Configure Gravitee service files"
  template: 
    src: templates/gravitee_service.j2   
    dest: /etc/systemd/system/graviteeio-apim-{{ item }}.service
  loop:
    - gateway
    - rest-api
- name: "Configure Gravitee console UI constants file"
  template: 
    src: gravitee_console_ui_constants.json.j2   
    dest: "{{ gravitee_install_dir }}/console-ui/constants.json"

- name: "Start Gravitee services"
  systemd: 
    name: graviteeio-apim-{{ item }}.service
    state: restarted
    enabled: true
  loop:
    - gateway
    - rest-api

- name: "Wait until Gravitee's ElasticSearch indices are created"
  ansible.builtin.uri:
    method: GET
    url: http://localhost:9200/_cat/indices/gravitee*?format=json
  register: es_indices_list
  until: es_indices_list.status == 200 and es_indices_list.json|length > 0
  retries: 10
  delay: 3

- name: "Configure Gravitee's ElasticSearch Index template"
  ansible.builtin.uri:
    method: PUT
    url: http://localhost:9200/_index_template/gravitee_indices
    body_format: json
    body: |
      {
        "template": {
          "settings": {
            "index": {
              "lifecycle": {
                "name": "gravitee-indices"
              },
              "number_of_replicas": "0"
            }
          }
        },
        "index_patterns": [
          "gravitee-health-*",
          "gravitee-log-*",
          "gravitee-monitor-*",
          "gravitee-request-*"
        ],
        "composed_of": []
      }

- name: "Configure Gravitee's ElasticSearch indices policies"
  ansible.builtin.uri:
    method: PUT
    url: http://localhost:9200/_ilm/policy/gravitee-indices
    body_format: json
    body: |
      {
        "policy": {
          "phases": {
            "hot": {
              "actions": {
                "rollover": {
                  "max_age": "30d",
                  "max_primary_shard_size": "50gb"
                },
                "set_priority": {
                  "priority": 100
                }
              },
              "min_age": "0ms"
            },
            "delete": {
              "min_age": "30d",
              "actions": {
                "delete": {}
              }
            }
          }
        }
      }
