---
- name: Add Elasticsearch apt key.
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  ansible.builtin.apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true

- name: Install Elasticsearch
  ansible.builtin.package:
    name: elasticsearch=7.17.9
    state: present
- name: Setting sysctl
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: 262144

- name: Start Elasticsearch.
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: true

- name: Make sure Elasticsearch is running before proceeding.
  ansible.builtin.wait_for:
    host: localhost
    port: 9200
    delay: 3
    timeout: 300