---
- name: "Create Gravitee user"
  ansible.builtin.user:
    name: gravitee
    system: true
    home: "{{ gravitee_install_dir }}"
    create_home: true
    state: present
    shell: /bin/nologin
  become: true
- name: "Download and install Gravitee {{ gravitee_version }}"
  block:
    - name: "Define Gravitee release URL"
      ansible.builtin.set_fact:
        gravitee_release_download_url: "https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ gravitee_version }}.zip"

    - name: "Download Gravitee archive"
      ansible.builtin.get_url:
        url: "{{ gravitee_release_download_url }}"
        dest: "/tmp/gravitee-{{ gravitee_version }}.zip"
        checksum: "sha1:{{ gravitee_release_download_url }}.sha1"
        mode: '0444'

    - name: "Ensure install dir exists"
      ansible.builtin.file:
        path: "{{ gravitee_install_dir }}"
        state: directory
        mode: '0775'
        owner: "{{ gravitee_service_user }}"
        group: "{{ gravitee_service_user }}"
      become: true

    - name: "Extract archive"
      ansible.builtin.unarchive:
        src: "/tmp/gravitee-{{ gravitee_version }}.zip"
        dest: "/tmp"
        remote_src: true  
    - name: move files to install directory
      ansible.builtin.copy:
        src: "/tmp/graviteeio-full-{{ gravitee_version }}/"
        dest: "{{ gravitee_install_dir }}"
        owner: "{{ gravitee_service_user }}"
        group: "{{ gravitee_service_user }}"
        remote_src: true
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ gravitee_install_dir }}/graviteeio-apim-{{ item }}-{{ gravitee_version }}"
        dest: "{{ gravitee_install_dir }}/{{item }}"
        owner: "{{ gravitee_service_user }}"
        group: "{{ gravitee_service_user }}"
        state: link
      loop:
        - console-ui
        - gateway
        - portal-ui
        - rest-api
  rescue:
    - name: Cleanup folder to allow new installation
      ansible.builtin.file:
        path: release_folder.stat.path
        state: absent
      become: true